CC=gcc
CFLAGS=-g

all : challenge1 challenge2 challenge3 challenge4 challenge5

challenge1: base64.o crypto-utils.o

challenge2: base64.o crypto-utils.o

challenge3: crypto-utils.o xor-utils.o

challenge4: crypto-utils.o xor-utils.o

challenge5: crypto-utils.o xor-utils.o

clean:
	rm *.o challenge1 challenge2 challenge3 challenge4 challenge5
